name: Testing API
on:
  workflow_dispatch:
  push:
    branches:
      - workflow_testing_app
  pull_request:
    branches:
      - workflow_testing_app
permissions:
  id-token: write
  contents: read

jobs:
  testing-api:
    name: Testing-api on Github Actions
    run-on: ubuntu-lates
    steps:
      - name: Checkouttherepo
        uses: actions/checkout@v3

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-session-name: aws_testing_session
          role-to-assume: ${{secrets.AWS_IAM_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Creating and activating environment with pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install
          pipenv run python
      - name: Installing dependencies
        run: |
          pip install dvc[s3]
          pip install -r requirements_test.txt
      - name: TestAPI
        run: |
          dvc pull model/model.pkl -r model-tracker
          pytest tests/tests_api.py